;; Problem #12 
;; The sequence of triangle numbers is generated by adding the natural numbers.
;; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
;; The first ten terms would be: ...
;; Let us list the factors of the first seven triangle numbers:
;; We can see that 28 is the first triangle number to have over five divisors.
;; What is the value of the first triangle number to have over 
;; five hundred divisors?

(add-to-load-path ".")
(use-modules (euler-module))   ; factor, group-factors, number-of-divisors

(define (group-factor-triangle i)
  (let* ((gfi (if (even? i)
               (group-factors (factors (quotient i 2)))
               (group-factors (factors i))))
        (gfi1 (if (even? i) ; odd i+1
                (group-factors (factors (1+ i)))
                (group-factors (factors (quotient (1+ i) 2)))))
       (gf (append gfi gfi1)))
       (number-of-divisors gf)))

(define (e012 i limit)
  (if (> (group-factor-triangle i) limit)
    (quotient (* i (1+ i)) 2)
    (e012 (1+ i) limit)))

;(e012 4 20)
(display (e012 4 500))
